import Head from 'next/head';
import Image from 'next/image';

import { useState, useEffect } from 'react';

import Nav from '../components/Nav';
import Projets from '../components/Projets';

import Bubbles from '../components/Bubbles';
import photoMoi from '../public/img/me.jpg';

export default function Home() {
  const [projectsHovered, setProjectsHovered] = useState({
    codingtutors: false,
    mathieuhue: false,
    collectifregina: false,
    rethacolt: false,
    leproductif: false,
    gabrielg: false,
    photomoi: false,
  });

  const [activeThemeName, setActiveThemeName] = useState(null);
  const [activeSection, setActiveSection] = useState(null);

  useEffect(() => {
    const checkClassNameHovered = () => {
      for (let [key, value] of Object.entries(projectsHovered)) {
        if (value) {
          return key;
        }
      }
    };

    setActiveThemeName(checkClassNameHovered());
  }, [projectsHovered]);

  useEffect(() => {
    window.addEventListener('scroll', function () {
      const observable = {
        home: document.querySelector('.home'),
        about: document.querySelector('.about'),
        work: document.querySelector('.work'),
        contact: document.querySelector('.contact'),
      };

      const pos = {
        home: observable.home.getBoundingClientRect(),
        about: observable.about.getBoundingClientRect(),
        work: observable.work.getBoundingClientRect(),
        contact: observable.contact.getBoundingClientRect(),
      };

      console.log(window.innerHeight, pos.about.top);

      if (pos.home.top < window.innerHeight && pos.home.bottom >= 400) {
        setActiveSection('home');
      } else if (
        pos.about.bottom < window.innerHeight &&
        pos.about.bottom >= 400
      ) {
        setActiveSection('about');
      } else if (pos.work.top < window.innerHeight && pos.work.bottom >= 400) {
        setActiveSection('work');
      } else if (
        pos.contact.top < window.innerHeight &&
        pos.contact.bottom >= 400
      ) {
        setActiveSection('contact');
      }
    });

    return () => {
      window.removeEventListener('scroll', () => console.log('yo'));
    };
  }, []);

  const setImageHovered = (boolean) => {
    setProjectsHovered({ ...projectsHovered, ['photomoi']: boolean });
  };

  console.log(activeThemeName);

  return (
    <div>
      <Head>
        <title>Gabriel | Développeur Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav activeThemeName={activeThemeName} activeSection={activeSection} />
      <main className="layout">
        <div
          className={`home ${
            activeThemeName ? `home--${activeThemeName}` : ''
          }`}
          id="home"
        >
          <Bubbles activeThemeName={activeThemeName} />
          <p className="home__title">
            Hey, <br />
            Je suis
            <span className="home__title__span"> Gabriel</span>, <br />
            développeur web
          </p>
          <p className="home__description">
            Je suis un développeur web passionné par le design et la création de
            sites web qui véhiculent un message sensé.
          </p>
          <a href="#contact" className="home__link">
            <button className="button__style--1__medium">
              Contactez-moi !
            </button>
          </a>
          <a href="#work" className="arrow-container__link">
            <div className="arrow-container animated fadeInDown">
              <div className="arrow-2">
                <i className="fa fa-angle-down"></i>
              </div>
              <div className="arrow-1 animated hinge infinite zoomIn"></div>
            </div>
          </a>
        </div>

        <Projets
          projectsHovered={projectsHovered}
          setProjectsHovered={setProjectsHovered}
          activeThemeName={activeThemeName}
        />

        <section
          className={`about ${
            activeThemeName ? `about--${activeThemeName}` : ''
          }`}
          id="about"
        >
          <div className="about__container">
            <div className="about__infos">
              <p className="about__title">
                <span
                  className={`about__title__span ${
                    activeThemeName
                      ? `about__title__span--${activeThemeName}`
                      : ''
                  }`}
                >
                  {'> '}
                </span>
                Qui suis-je ?
              </p>
              <div
                className={`about__description ${
                  activeThemeName
                    ? `about__description--${activeThemeName}`
                    : ''
                }`}
              >
                En tant que développeur frontend junior, j'ai eu l'occasion
                d'expérimenter plusieurs technologies frontend et backend sur
                les différents projets sur lesquels j'ai pu travailler. <br />
                <br />
                L'approche pragmatique et artistique nécessaires à la conception
                de sites web sont ce qui me plaît le plus. Ce mélange
                intéressant de qualités que demandent le design et création d'un
                site web fait directement écho au travail de l'artisan,
                minutieusement travaillé et inventif.
                <br /> <br />
                J'approche chacun des projets qui me sont confiés avec rigueur
                et communication.
              </div>
            </div>
            <div
              className={`about__image ${
                activeThemeName ? `about__image--${activeThemeName}` : ''
              }`}
              onMouseEnter={() => setImageHovered(true)}
              onMouseLeave={() => setImageHovered(false)}
            >
              {/* <div
                className={`about__image__container ${
                  activeThemeName
                    ? `about__image__container--${activeThemeName}`
                    : ''
                }`}
                onMouseEnter={() => setProjectHover(true)}
                onMouseLeave={() => setProjectHover(false)}
              > */}
              <Image
                src={photoMoi}
                width="1500"
                height="1500"
                layout="fill"
                objectFit="cover"
              />
              {/* </div> */}
            </div>
          </div>
        </section>
        <section
          className={`contact ${
            activeThemeName ? `contact--${activeThemeName}` : ''
          }`}
          id="contact"
        >
          <div
            className={`contact__title ${
              activeThemeName ? `contact__title--${activeThemeName}` : ''
            }`}
          >
            <span
              className={`contact__title__span ${
                activeThemeName
                  ? `contact__title__span--${activeThemeName}`
                  : ''
              }`}
            >
              {'> '}
            </span>
            Me contacter
          </div>
          <div className="contact__description">
            Si vous souhaitez me parler à propos d'un projet ou si vous avez une
            question, n'hésitez pas à me contacter :-{')'}
          </div>
          <a href="mailto:garcia.gvj@gmail.com">
            <button className="button__style--1__small">Contactez-moi !</button>
          </a>
        </section>
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
